import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronLeft, ChevronRight, Download, Play, Pause, RotateCcw, ArrowLeft } from 'lucide-react';
import { ShoeVideoGeneration } from '../types';

interface VideoVisualizationProps {
  videoGenerations: ShoeVideoGeneration[];
  onBackToVisualizations?: () => void;
  onSearchProducts?: () => void;
}

const VideoVisualization: React.FC<VideoVisualizationProps> = ({ videoGenerations, onBackToVisualizations, onSearchProducts }) => {
  const [currentShoeIndex, setCurrentShoeIndex] = useState(0);
  const [currentVideoIndex, setCurrentVideoIndex] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);

  const currentShoe = videoGenerations[currentShoeIndex];
  const currentVideo = currentShoe?.videos[currentVideoIndex];

  const nextShoe = () => {
    setCurrentShoeIndex((prev) => (prev + 1) % videoGenerations.length);
    setCurrentVideoIndex(0);
    setIsPlaying(false);
  };

  const prevShoe = () => {
    setCurrentShoeIndex((prev) => (prev - 1 + videoGenerations.length) % videoGenerations.length);
    setCurrentVideoIndex(0);
    setIsPlaying(false);
  };

  const nextVideo = () => {
    setCurrentVideoIndex((prev) => (prev + 1) % currentShoe.videos.length);
    setIsPlaying(false);
  };

  const prevVideo = () => {
    setCurrentVideoIndex((prev) => (prev - 1 + currentShoe.videos.length) % currentShoe.videos.length);
    setIsPlaying(false);
  };

  const downloadVideo = () => {
    if (currentVideo?.video_url) {
      const link = document.createElement('a');
      link.href = currentVideo.video_url;
      link.download = `${currentShoe.shoe.brand}_${currentShoe.shoe.name}_${currentVideo.angle}.mp4`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    }
  };

  const togglePlayPause = () => {
    setIsPlaying(!isPlaying);
  };

  if (videoGenerations.length === 0) return null;

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="w-full max-w-6xl mx-auto"
    >
      <div className="bg-white/95 backdrop-blur-sm rounded-3xl shadow-2xl p-6 md:p-8 border border-white/20">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-3">
            {onBackToVisualizations && (
              <button
                onClick={onBackToVisualizations}
                className="p-2 rounded-full bg-gray-100 hover:bg-gray-200 transition-colors mr-2"
              >
                <ArrowLeft className="w-5 h-5 text-gray-600" />
              </button>
            )}
            <div className="bg-gradient-to-r from-purple-500 to-pink-500 p-3 rounded-xl">
              <Play className="w-6 h-6 text-white" />
            </div>
            <div>
              <h2 className="text-2xl font-bold text-gray-800">
                Live Fit Check Videos
              </h2>
              <p className="text-gray-600">
                Generated by FAL AI Veo3
              </p>
            </div>
          </div>
          
          <div className="flex gap-3">
            {onSearchProducts && (
              <button
                onClick={onSearchProducts}
                className="bg-gradient-to-r from-blue-500 to-blue-600 hover:from-blue-600 hover:to-blue-700 text-white px-4 py-2 rounded-xl font-semibold transition-all duration-300 flex items-center gap-2"
              >
                🔍 Buy Shoes
              </button>
            )}
            <button
              onClick={downloadVideo}
              className="bg-gradient-to-r from-purple-500 to-pink-500 text-white px-4 py-2 rounded-xl font-semibold hover:from-purple-600 hover:to-pink-600 transition-all duration-300 flex items-center gap-2"
            >
              <Download className="w-4 h-4" />
              Download
            </button>
          </div>
        </div>

        {/* Shoe Navigation */}
        <div className="flex items-center justify-between mb-6">
          <button
            onClick={prevShoe}
            className="p-3 rounded-full bg-gray-100 hover:bg-gray-200 transition-colors"
          >
            <ChevronLeft className="w-5 h-5 text-gray-600" />
          </button>
          
          <div className="text-center">
            <h3 className="text-xl font-bold text-gray-800">
              {currentShoe.shoe.brand} {currentShoe.shoe.name}
            </h3>
            <p className="text-gray-600">
              {currentShoe.shoe.color} • {currentShoe.shoe.style}
            </p>
          </div>
          
          <button
            onClick={nextShoe}
            className="p-3 rounded-full bg-gray-100 hover:bg-gray-200 transition-colors"
          >
            <ChevronRight className="w-5 h-5 text-gray-600" />
          </button>
        </div>

        {/* Main Video Display */}
        <div className="bg-gradient-to-br from-gray-50/80 to-gray-100/80 rounded-2xl p-6 mb-6 backdrop-blur-sm">
          <div className="flex items-center justify-between mb-4">
            <h4 className="text-lg font-semibold text-gray-800">
              {currentVideo?.angle.toUpperCase()} View
            </h4>
            
            <div className="flex gap-2">
              <button
                onClick={prevVideo}
                className="p-2 rounded-full bg-white hover:bg-gray-50 transition-colors"
              >
                <RotateCcw className="w-4 h-4 text-gray-600" />
              </button>
              <button
                onClick={nextVideo}
                className="p-2 rounded-full bg-white hover:bg-gray-50 transition-colors"
              >
                <RotateCcw className="w-4 h-4 text-gray-600 rotate-180" />
              </button>
            </div>
          </div>
          
          <AnimatePresence mode="wait">
            <motion.div
              key={`${currentShoeIndex}-${currentVideoIndex}`}
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              transition={{ duration: 0.3 }}
              className="relative"
            >
              {currentVideo?.video_url && currentVideo.status === 'completed' ? (
                <div className="flex justify-center">
                  <div className="relative">
                    <video
                      src={currentVideo.video_url}
                      className="max-w-full max-h-80 w-auto h-auto object-contain rounded-lg bg-white shadow-sm"
                      style={{ maxWidth: '500px', maxHeight: '400px' }}
                      controls
                      autoPlay={isPlaying}
                      loop
                      muted
                    />
                    <button
                      onClick={togglePlayPause}
                      className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 bg-black/50 hover:bg-black/70 text-white p-3 rounded-full transition-all duration-300"
                    >
                      {isPlaying ? <Pause className="w-6 h-6" /> : <Play className="w-6 h-6" />}
                    </button>
                  </div>
                </div>
              ) : currentVideo?.status === 'failed' ? (
                <div className="flex justify-center items-center h-80 bg-gray-100 rounded-lg">
                  <div className="text-center text-gray-500">
                    <Play className="w-12 h-12 mx-auto mb-2 opacity-50" />
                    <p>Video generation failed</p>
                  </div>
                </div>
              ) : (
                <div className="flex justify-center items-center h-80 bg-gray-100 rounded-lg">
                  <div className="text-center text-gray-500">
                    <div className="w-12 h-12 border-4 border-gray-200 border-t-purple-500 rounded-full mx-auto mb-2 animate-spin" />
                    <p>Generating video...</p>
                  </div>
                </div>
              )}
            </motion.div>
          </AnimatePresence>
        </div>

        {/* Video Navigation */}
        <div className="flex justify-center gap-2 mb-6">
          {currentShoe.videos.map((video, index) => (
            <button
              key={index}
              onClick={() => setCurrentVideoIndex(index)}
              className={`px-4 py-2 rounded-lg font-medium transition-colors ${
                index === currentVideoIndex
                  ? 'bg-purple-500 text-white'
                  : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
              }`}
            >
              {video.angle.toUpperCase()}
            </button>
          ))}
        </div>

        {/* Shoe Thumbnails */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {videoGenerations.map((shoeViz, shoeIndex) => (
            <motion.div
              key={shoeIndex}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: shoeIndex * 0.1 }}
              onClick={() => {
                setCurrentShoeIndex(shoeIndex);
                setCurrentVideoIndex(0);
                setIsPlaying(false);
              }}
              className={`p-4 rounded-xl border-2 cursor-pointer transition-all duration-300 ${
                shoeIndex === currentShoeIndex
                  ? 'border-purple-500 bg-purple-50'
                  : 'border-gray-200 bg-white hover:border-gray-300 hover:shadow-md'
              }`}
            >
              <div className="text-center">
                <div className="w-16 h-16 mx-auto mb-3 bg-gradient-to-br from-purple-400 to-pink-400 rounded-xl flex items-center justify-center text-2xl">
                  🎬
                </div>
                <h5 className="font-semibold text-gray-800 text-sm mb-1">
                  {shoeViz.shoe.brand}
                </h5>
                <p className="text-xs text-gray-600 mb-2">
                  {shoeViz.shoe.name}
                </p>
                <div className="flex justify-center gap-1">
                  {shoeViz.videos.map((video, videoIndex) => (
                    <div
                      key={videoIndex}
                      className={`w-2 h-2 rounded-full ${
                        shoeIndex === currentShoeIndex && videoIndex === currentVideoIndex
                          ? 'bg-purple-500'
                          : video.status === 'completed'
                          ? 'bg-green-400'
                          : video.status === 'failed'
                          ? 'bg-red-400'
                          : 'bg-yellow-400'
                      }`}
                    />
                  ))}
                </div>
              </div>
            </motion.div>
          ))}
        </div>

        {/* Shoe Details */}
        <div className="mt-6 p-4 bg-gray-50/80 rounded-2xl backdrop-blur-sm">
          <h4 className="font-semibold text-gray-800 mb-2">
            Why this shoe works:
          </h4>
          <p className="text-gray-700">
            {currentShoe.shoe.reason}
          </p>
        </div>
      </div>
    </motion.div>
  );
};

export default VideoVisualization;
